### ISSUE TITLE
Macos

### ISSUE THREAD

**Issue by Geert-Jan77** [AndreRenaud/PDFGen#109]
MacOS has a special way of doing `fprintf (%f, 3.14) ` It always has the same output: `3,14`. This does not depend of the locale. This results in a damaged pdf. I have solved it in my own project [Side Cutters, free CAD software](https://github.com/Geert-Jan77/sidecutters), see [issue](https://github.com/Geert-Jan77/sidecutters/issues/2) .

**Comment by AndreRenaud** [comment]
Thanks for catching this. You say it's not dependent on the locale - can you confirm this is what you meant? This feels very much like a locale issue. I'm running Macos, and do not see this issue, but my locale is set to en_NZ.UTF-8. Can you confirm if the issue persists of you run `export LC_NUMERIC="en_US.UTF-8"` before running the software?

**Comment by AndreRenaud** [comment]
I've had a poke around and been able to replicate the issue - the change at https://github.com/AndreRenaud/PDFGen/pull/110 fixes it for me by saving/restoring the locale. It might be a bit heavy handed, but should resolve the issue. Are you able to check/confirm?

**Comment by Geert-Jan77** [comment]
I confirm the locale sets the behaviour of `fprintf("This comma should be a dot %f", 6.54321f);`
There is a big difference in how the locale is set:

1. The locale is selected when the operating system is installed.
2. In the build system. 
`export LC_NUMERIC="en_US.UTF-8"` On the next OS startup, the value will get override from 1)
3. In the code.
`setlocale(LC_NUMERIC, "C");` Like it is done at #110. On the start of a new instance, the value will get override from 2)

On your system, you can replicate the error if you try really hard, because eventually 1) always overrides the locale. The power of `pdfgen.c` is that it works on every platform on every build system, so i would say the issue must be solved in the code by replacing the comma with a dot: issue https://github.com/Geert-Jan77/sidecutters/issues/2

**Comment by AndreRenaud** [comment]
Hi,
I'm not entirely sure I follow your procedure there. Are you able to replicate the issue with the code on that branch? I was able to replicate it before on MacOs (and Linux), and am unable to do so after I made the changes. I'd rather not do the comma/dot replacement scheme, because it would have to go into a lot of places in the code (everywhere %f is used in a printf formatter). I replicated it on MacOS by changing my region in the control panel, rather than setting LC_ALL or LANG environment variables manually (although I tested like that as well).

Regarding the bounding box - the fonts that pdfgen supports are the ones that come pre-supported in all PDFs. It's really an old system - newer PDF engines embed the font itself into the document (pdfgen doesn't support this at the moment). That means that the font support is pretty limited. Essentially that means you can only use the 14 standard fonts - https://en.wikipedia.org/wiki/PDF#Text https://kbpdfstudio.qoppa.com/standard-14-pdf-fonts/

**Comment by AndreRenaud** [comment]
I'm going to tag this as closed having merged #110 . Please reopen if the issue persists. Thanks.
