### ISSUE TITLE
Feature request: transparent text 

### ISSUE THREAD

**Issue by ignatz** [AndreRenaud/PDFGen#15]
I was hoping to overlay some transparent text in my pdf. I noticed that pdf_add_text_spacing() supports only RGB. A played a little trying to emit the right commands but my pdf foo isn't strong enough to set the alpha correctly :/ - maybe it's super easy for you.

**Comment by AndreRenaud** [comment]
Could you flick through a couple of lines of code that demonstrate the issue?

**Comment by ignatz** [comment]
Sure thing, e.g.:
// sorry c++
#include <fstream>

extern "C" {
#include <pdfgen.h>
}

int main() {
  pdf_info info = {/*.creator =*/"My software",
                   /*.producer =*/"My software",
                   /*.title =*/"My document",
                   /*.author =*/"My name",
                   /*.subject =*/"My subject",
                   /*.date =*/"Today"};
  pdf_doc *pdf = pdf_create(PDF_A4_WIDTH, PDF_A4_HEIGHT, &info);
  pdf_set_font(pdf, "Times-Roman");
  pdf_append_page(pdf);
  pdf_add_text(pdf, NULL, "This is text", 12, 50, 20, PDF_TRANSPARENT);
  pdf_save(pdf, "output.pdf");
  pdf_destroy(pdf);

  return 0;
}

produces a pdf with black text.

Sorry for going on a tangent, just something I just noticed:
 1. your example in the pdfgen.h is missing the color argument
 2. you're missing a <stdio.h> include, i.e. FILE is undeclared

**Comment by AndreRenaud** [comment]
Can you have a look at the new 'transparency' branch?
https://github.com/AndreRenaud/PDFGen/tree/transparency
It's a bit clunky - I just take the top 4-bits of the transparency and have 16 graphics states with differing level of transparency (from opaque to fully transparent). So 0x80 and 0x8f will end up being the same level of transparency, but 0x90 will be one level up.
If this is sufficient, I'll go ahead with it because it's a fairly minimal change.

**Comment by ignatz** [comment]
Works like a charm. Just what I was looking for. Thanks so much!

**Comment by AndreRenaud** [comment]
No problem.
