### ISSUE TITLE
position (yoff) bug?

### ISSUE THREAD

**Issue by silvioprog** [AndreRenaud/PDFGen#3]
Hello.

First, thanks for this great work!

So, I'm testing the following example:

```c
#include <stdio.h>
#include "pdfgen.h"

int main() {
    struct pdf_doc *pdf = pdf_create(PDF_A4_WIDTH, PDF_A4_HEIGHT, NULL);
    pdf_append_page(pdf);
    pdf_set_font(pdf, "Times-Roman");
    pdf_add_text(pdf, NULL, "This is text", 48, 0, 0, 0);
    pdf_save(pdf, "output.pdf");
    pdf_destroy(pdf);
    return 0;
}
```

and it generates the following page:

![image](https://user-images.githubusercontent.com/1456829/36624613-1b4a6538-18f0-11e8-8c55-33e9d8bdd25f.png)

it is OK for `x = 0`, however, for the `y = 0`, it should generate as the following one:

![image](https://user-images.githubusercontent.com/1456829/36624632-519a4928-18f0-11e8-9cee-ecbb22e71df9.png)

what I'm doing wrong? :confused:

**Comment by AndreRenaud** [comment]
I don't think you're doing anything wrong. PDF documents have a coordinate system where 0,0 is the bottom left of the page, not the top left like on most graphics displays. So the output you're seeing looks right to me.

**Comment by AndreRenaud** [comment]
I'll close this off now, since I think it's probably behaving as expected. Feel free to reopen if I've missed anything or you think I'm mistaken. Thanks.

**Comment by silvioprog** [comment]
Thanks dude! :+1:

**Comment by mcfriend99** [comment]
This is causing text added by `pdf_add_text_wrap` to go from bottom to top. Lorem ipsum became:

```
culpa qui officia deserunt mollit anim id est laborum.
reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in 
ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in 
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
```

As you can see, it's the reverse. I don't think it's what users expect.

**Comment by AndreRenaud** [comment]
Can you post a snippet of the code you're running that causes that? I agree, it obviously should wrap down the page, but that's why the yoff position is reduced, not increased, at each line: https://github.com/AndreRenaud/PDFGen/blob/master/pdfgen.c#L1923


You can see the example code here: https://github.com/AndreRenaud/PDFGen/blob/master/tests/main.c#L81 which wraps down the page, not in reverse:
<img width="339" alt="Screenshot 2023-04-02 at 11 20 55 AM" src="https://user-images.githubusercontent.com/2322636/229321651-ef356894-60d4-43e7-9bd6-2164fe11bdc7.png">
